url_fetch: "http://141.45.212.246:8000/measurements/all"
url_predict: "http://141.45.212.246:8000/measurements/predict"

num_measurements: -1
rooms: ["WH_C_351", "WH_C_352", "WH_C_353", "WH_C_335"]
corridors: ["WH_C_35_corridor"]

parameter_sets:
  - name: "01_knn_weights"
    parameters:
      router_selection: ["all"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none"]
      weights: ["distance", "uniform"]
      algorithm:
        knn_euclidean:
          k_value: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
        knn_sorensen:
          k_value: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
  - name: "02_svm_gamma_value"
    parameters:
      router_selection: ["all"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none"]
      gamma_value: ["scale", "auto"]
      algorithm:
        svm_rbf:
          c_value: [0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0]
  - name: "03_random_forest_max_depth"
    parameters:
      router_selection: ["all"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none"]
      algorithm:
        random_forest:
          max_depth: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, "None"]
  - name: "04_random_forest_n_estimators"
    parameters:
      router_selection: ["all"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none"]
      max_depth: [9]
      algorithm:
        random_forest:
          n_estimators:
            [
              10,
              20,
              30,
              40,
              50,
              60,
              70,
              80,
              90,
              100,
              200,
              300,
              400,
              500,
              600,
              700,
              800,
              900,
              1000,
            ]
  - name: "05_best_parameters_all"
    parameters:
      router_selection: ["all"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none"]
      weights: ["distance"]
      algorithm:
        knn_euclidean:
          k_value: [1, 3, 5, 7, 9, 11, 13, 15]
        knn_sorensen:
          k_value: [1, 3, 5, 7, 9, 11, 13, 15]
        svm_linear:
          c_value: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0]
        svm_rbf:
          c_value: [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0]
  - name: "05_best_parameters_random_forest"
    parameters:
      router_selection: ["all"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none"]
      n_estimators: [50]
      max_depth: [9]
      algorithm:
        random_forest:
          max_features:
            [
              "sqrt",
              "log2",
              "None",
              0.1,
              0.2,
              0.3,
              0.4,
              0.5,
              0.6,
              0.7,
              0.8,
              0.9,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
            ]
  - name: "06_handle_missing_values_strategy"
    parameters:
      router_selection: ["all"]
      handle_missing_values_strategy: ["zero", "-100", "use_received"]
      router_presence_threshold: [0]
      value_scaling_strategy: ["none"]
      n_estimators: [50]
      max_depth: [9]
      algorithm:
        knn_euclidean:
          k_value: [5, 7, 9]
        knn_sorensen:
          k_value: [5, 7, 9]
        random_forest:
          max_features: [0.8, 2, 8]
        svm_linear:
          c_value: [0.001, 0.005, 0.01]
        svm_rbf:
          c_value: [5.0, 1.0, 0.5]
  - name: "07_router_selection"
    parameters:
      router_selection: ["all", "eduroam"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      value_scaling_strategy: ["none"]
      n_estimators: [50]
      max_depth: [9]
      algorithm:
        knn_euclidean:
          k_value: [5, 7, 9]
        knn_sorensen:
          k_value: [5, 7, 9]
        random_forest:
          max_features: [0.8, 2, 8]
        svm_linear:
          c_value: [0.001, 0.005, 0.01]
        svm_rbf:
          c_value: [5.0, 1.0, 0.5]
  - name: "08_router_presence_threshold"
    parameters:
      router_selection: ["eduroam"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0, 0.25, 0.5, 0.75]
      value_scaling_strategy: ["none"]
      n_estimators: [50]
      max_depth: [9]
      algorithm:
        knn_euclidean:
          k_value: [5, 7, 9]
        knn_sorensen:
          k_value: [5, 7, 9]
        random_forest:
          max_features: [0.8, 2, 8]
        svm_linear:
          c_value: [0.001, 0.005, 0.01]
        svm_rbf:
          c_value: [5.0, 1.0, 0.5]
  - name: "09_router_rssi_threshold"
    parameters:
      router_selection: ["eduroam"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100, -90, -80, -70, -60, -50, -40]
      value_scaling_strategy: ["none"]
      n_estimators: [50]
      max_depth: [9]
      algorithm:
        knn_euclidean:
          k_value: [5, 7, 9]
          router_presence_threshold: [0]
        knn_sorensen:
          k_value: [5, 7, 9]
          router_presence_threshold: [0]
        random_forest:
          max_features: [0.8, 2, 8]
          router_presence_threshold: [0]
        svm_linear:
          c_value: [0.001, 0.005, 0.01]
          router_presence_threshold: [0.25]
        svm_rbf:
          c_value: [5.0, 1.0, 0.5]
          router_presence_threshold: [0.25]
  - name: "10_knn_weights_value_scaling_strategy"
    parameters:
      router_selection: ["eduroam"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100, -90, -80, -70, -60, -50, -40]
      value_scaling_strategy: ["none", "exponential", "powed", "positive"]
      weights: ["distance", "uniform"]
      algorithm:
        knn_euclidean:
          k_value: [5, 7, 9]
        knn_sorensen:
          k_value: [5, 7, 9]
  - name: "11_value_scaling_strategy"
    parameters:
      router_selection: ["eduroam"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none", "exponential", "powed", "positive"]
      n_estimators: [50]
      max_depth: [9]
      algorithm:
        knn_euclidean:
          k_value: [5, 7, 9]
          router_presence_threshold: [0]
        knn_sorensen:
          k_value: [5, 7, 9]
          router_presence_threshold: [0]
        random_forest:
          max_features: [0.8, 2, 8]
          router_presence_threshold: [0]
        svm_linear:
          c_value: [0.001, 0.005, 0.01]
          router_presence_threshold: [0.25]
        svm_rbf:
          c_value: [5.0, 1.0, 0.5]
          router_presence_threshold: [0.25]
  - name: "12_corridor"
    parameters:
      router_selection: ["eduroam"]
      handle_missing_values_strategy: ["-100"]
      router_presence_threshold: [0]
      router_rssi_threshold: [-100]
      value_scaling_strategy: ["none"]
      measurements_per_room: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
      measurements_per_corridor: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
      weights: ["distance"]
      algorithm:
        knn_sorensen:
          k_value: [5]
